//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Q_DOWNLOAD.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_Q_DOWNLOAD_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_INITIAL                     129
#define IDD_SO                          130
#define IDD_PASSWORD                    131
#define IDB_BITMAP_RESET                132
#define IDB_BITMAP_SAVE                 133
#define IDB_BITMAP_START                134
#define IDB_BITMAP_CONFIG               135
#define IDB_BITMAP_EXIT                 136
#define IDB_BITMAP_OK                   137
#define IDD_CONFIG                      139
#define IDB_BITMAP_STOP                 141
#define IDC_TITLE                       1000
#define IDC_STATIC_PARTITION            1001
#define IDC_STATIC_Hex                  1002
#define IDC_STATIC_OEMSBLH              1003
#define IDC_STATIC_SO                   1004
#define IDC_STATIC_OEMSBL               1005
#define IDC_STATIC_AMSSH                1006
#define IDC_STATIC_QCSBLH               1007
#define IDC_STATIC_TOTAL                1008
#define IDC_STATIC_QCSBL                1009
#define IDC_STATIC_AMSS                 1010
#define IDC_STATIC_PASS                 1014
#define IDC_STATIC_FAIL                 1015
#define IDC_BUTTON_RESET                1016
#define IDC_STATIC_SW                   1017
#define IDC_STATIC_HW                   1018
#define IDC_PROGRESS_SUB1               1019
#define IDC_PROGRESS_SUB2               1020
#define IDC_PROGRESS_SUB3               1021
#define IDC_PROGRESS_SUB4               1022
#define IDC_PROGRESS_SUB5               1023
#define IDC_PROGRESS_SUB6               1024
#define IDC_PROGRESS_SUB7               1025
#define IDC_PROGRESS_SUB8               1026
#define IDC_PROGRESS_MAIN1              1027
#define IDC_PROGRESS_MAIN2              1028
#define IDC_PROGRESS_MAIN3              1029
#define IDC_PROGRESS_MAIN4              1030
#define IDC_PROGRESS_MAIN5              1031
#define IDC_PROGRESS_MAIN6              1032
#define IDC_PROGRESS_MAIN7              1033
#define IDC_PROGRESS_MAIN8              1034
#define IDC_STATIC_COM3                 1035
#define IDC_STATIC_COM4                 1036
#define IDC_STATIC_COM5                 1037
#define IDC_STATIC_COM6                 1038
#define IDC_STATIC_COM7                 1039
#define IDC_STATIC_COM8                 1040
#define IDC_STATIC_COM9                 1041
#define IDC_STATIC_COM10                1042
#define IDC_STATIC_PROGRESS1            1043
#define IDC_STATIC_PROGRESS2            1044
#define IDC_STATIC_PROGRESS3            1045
#define IDC_STATIC_PROGRESS4            1046
#define IDC_STATIC_PROGRESS5            1047
#define IDC_STATIC_PROGRESS6            1048
#define IDC_STATIC_PROGRESS7            1049
#define IDC_STATIC_PROGRESS8            1050
#define IDC_LIST_MESSAGE                1051
#define IDC_COMBO_MODEL                 1052
#define IDC_COMBO_SW                    1053
#define IDC_COMBO_MODE                  1054
#define IDC_COMBO_HW                    1055
#define IDC_COMBO_PARTITION             1056
#define IDC_COMBO_HEX                   1057
#define IDC_COMBO_QCSBL                 1058
#define IDC_COMBO_QCSBLH                1059
#define IDC_COMBO_OEMSBL                1060
#define IDC_COMBO_OEMSBLH               1061
#define IDC_COMBO_AMSS                  1062
#define IDC_COMBO_AMSSH                 1063
#define IDC_TEST                        1065
#define IDC_WRITEQFUSEFLAG              1067
#define IDC_COMBO_QVCEFS_FILE           1068
#define IDC_WRITEQFUSEFLAG2             1069
#define IDC_STATIC_PCNAME               1070
#define IDC_DL_MAINCODE                 1070
#define IDC_SO_NUMBER                   1071
#define IDC_DL_QVCEFS                   1071
#define IDC_EDIT_PASSWORD               1072
#define IDSAVE                          1072
#define PASSWORD                        1073
#define IDC_CONFIG                      1073
#define IDC_BUTTON_START                1074
#define IDC_BUTTON_EXIT                 1075
#define IDC_STATIC_QVCEFS               1076
#define IDC_QVCEFS_TIME                 1078
#define IDC_QVCEFS_SIZE                 1080
#define IDC_STATIC1                     1082
#define IDC_STATIC2                     1083
#define IDC_STATIC3                     1084
#define IDC_STATIC4                     1085
#define IDC_STATIC5                     1086
#define IDC_STATIC6                     1087
#define IDC_STATIC7                     1088
#define IDC_STATIC8                     1089
#define IDC_STATIC9                     1090
#define IDC_STATIC10                    1091
#define IDC_STATIC11                    1092
#define IDC_STATIC12                    1093
#define IDC_STATIC13                    1094
#define IDC_STATIC14                    1095
#define IDC_STATIC15                    1096
#define IDC_STATIC16                    1097
#define IDC_STATIC17                    1098
#define IDC_STATIC18                    1099
#define IDC_COMBO_TYPE                  1103
#define IDC_BACKUP_NV                   1104
#define IDC_WAITE_POWERON               1105
#define IDC_RESTART_TIMEOUT             1106
#define IDC_BUTTON1                     1107
#define IDC_BTN_Stop                    1107
#define IDC_BUTTON_STOP                 1107

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
