//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BlueObex.rc
//
#define IDC_EDIT_OBJECT                 2
#define IDC_CONNECT_BUTTON              3
#define IDC_NEW_OBJECT                  3
#define IDC_EDIT_SCRIPT                 3
#define IDC_OBJECTS_BUTTON              4
#define IDC_NEW_FROM_OBJECT             4
#define IDC_NEW_SCRIPT                  4
#define IDC_SCRIPTS_BUTTON              5
#define IDC_NEW_FROM_SCRIPT             5
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BLUEOBEX_DIALOG             102
#define IDD_OBEX_PROPPAGE_1             107
#define IDR_MAINFRAME                   128
#define IDD_CONNECTION_DIALOG           129
#define IDD_CHOOSE_SERVER_DIALOG        130
#define IDD_OBJECTS_DIALOG              131
#define IDD_SCRIPTS_DIALOG              133
#define IDB_BROADCOM                    134
#define IDD_OBEX_PROPPAGE_2             134
#define IDC_SERVER_CHECK                1000
#define IDC_STATUS_LABEL                1001
#define IDC_SEND_RECEIVE_LIST           1002
#define IDC_FOLDER_LABEL                1003
#define IDC_OBJECT_LABEL                1003
#define IDC_FOLDER_TEXT                 1004
#define IDC_STATUS_TEXT                 1009
#define IDC_SCRIPT_LABEL                1009
#define IDC_SCRIPT_TEXT                 1010
#define IDC_OBJECT_TEXT                 1010
#define IDC_SERVER_LIST                 1011
#define IDC_NAME_LABEL                  1011
#define IDC_NAME_TEXT                   1012
#define IDC_DESCR_LABEL                 1013
#define IDC_DESCR_TEXT                  1014
#define IDC_APPL_PARAM_LIST             1015
#define IDC_EDIT_PARAM_BUTTON           1016
#define IDC_ADD_PARAM_BUTTON            1017
#define IDC_CLOSE_PARAM_BUTTON          1018
#define IDC_DELETE_PARAM_BUTTON         1019
#define IDC_OBJECT_BUTTON               1020
#define IDC_SCRIPT_BUTTON               1021
#define IDC_START_BUTTON                1022
#define IDC_SEND_RECEIVE_LOG            1023
#define IDC_VERSION                     1024
#define IDC_COPYRIGHT                   1025

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
