//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BlueClient.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define ID_SET_TRUSTED                  101
#define IDD_BLUECLIENT_DIALOG           102
#define ID_SET_NONE_TRUSTED             102
#define IDS_INDICATOR_TIME              102
#define ID_PROPERTIES                   103
#define ID_SERVICES_STATUS              104
#define ID_REFRESH                      105
#define ID_REFRESH_NEIGHBORS            106
#define IDR_BTEXPLORER                  109
#define ID_REFRESH_FOLDERLISTING        110
#define ID_FTP_CHANGE_REMOTE_DIRECTORY  111
#define ID_FTP_DELETE_REMOTE_DIRECTORY  112
#define ID_FTP_GET_FILE                 113
#define ID_FTP_DELETE_FILE              114
#define ID_FTP_REMOTE_ROOT              115
#define ID_FTP_PUT_FILE                 116
#define ID_FTP_REMOTE_CREATE_FOLDER     117
#define ID_FTP_REMOTE_CREATE_FILE       118
#define IDR_MAINFRAME                   128
#define IDB_BROADCOM                    131
#define IDD_FTPCreate                   133
#define IDD_BT_EXP_DEV_PROPS            134
#define ID_FTP_ABORT                    135
#define IDC_BD_NAME                     202
#define IDB_BT_DEVICE_IMAGE             219
#define IDC_CLIENT_TREE                 1000
#define IDC_BROADCOM                    1001
#define IDC_VERSION                     1002
#define IDC_COPYRIGHT                   1003
#define IDC_BD_ADDR                     1187
#define IDC_LIST_SERVICE                1193
#define IDC_START                       1299
#define IDC_STOP                        1300
#define ID_PULL_VCARD                   1301
#define ID_EXCHANGE_VCARD               1302
#define ID_PUSH_VCARD                   1303
#define ID_PUSH_VCAL                    1304
#define ID_PUSH_VNOTE                   1305
#define ID_PUSH_VMESSAGE                1306
#define ID_REM_SERVICE0                 2000
#define ID_REM_SERVICE100               2100
#define ID_FIND_SERVICE0                2101
#define IDC_EDIT1                       3000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
