{Header
}
{Description
}
{Code
//Display red test
0000 waitinput %var1 COMPort
0001 Run MobileToolKit_StaticMD.dll DisplayTest %var1 "255" "0" "0" "255"
0002 comparetrue 0005
0003 print "Error on Display Red Test API"
0004 comparefalse 9999
0005 assign %var2 "Does Display Red Test success ?"
0006 waitinput %var2 ComfirmYesNo
0007 compare %var2 "Yes"
0008 comparefalse 9999
//0009 Run MobileToolKit_StaticMD.dll WriteMMIFlag %var1 385 1
//EM_BZ_ON_OFF_LCM 385
}