//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Calendar_Version2.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_CALENDAR_V2_FORM            101
#define IDS_BTN_ListPage_TIP            101
#define IDS_BTN_MonthPage_TIP           102
#define IDD_List_Page                   103
#define IDS_CALENDARVIEW_LISTCTRL_HEADER_CAPTION_1 103
#define IDS_CALENDARVIEW_LISTCTRL_HEADER_CAPTION_2 104
#define IDS_CALENDARVIEW_LISTCTRL_HEADER_CAPTION_3 105
#define IDS_CALENDARVIEW_LISTCTRL_HEADER_CAPTION_4 106
#define IDS_BTN_DayPage_TIP             107
#define IDS_BTN_WeekPage_TIP            108
#define IDR_MAINFRAME                   128
#define IDR_Calendar_V2TYPE             129
#define IDD_APPOINTMENTEDITOR_DIALOG    131
#define IDD_SYNCOUTLOOKDLG              132
#define IDC_Calendar_ListCtr            1009
#define IDC_Calendar_Tab                1010
#define IDC_BtnDownload                 1011
#define IDC_Calendar_DaytimeBox         1031
#define ID_APPOINTMENTEDITOR_BTN_OK     1032
#define ID_APPOINTMENTEDITOR_BTN_CANCEL 1033
#define IDC_APPOINTMENTEDITOR_EDIT_SUBJECT 1034
#define IDC_APPOINTMENTEDITOR_EDIT_LOCATION 1035
#define IDC_APPOINTMENTEDITOR_EDIT_ATTENDEES 1036
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT 1037
#define IDC_APPOINTMENTEDITOR_STATIC_LOCATION 1038
#define IDC_APPOINTMENTEDITOR_STATIC_ATTENDEES 1039
#define IDC_APPOINTMENTEDITOR_STATIC_DTSTART 1040
#define IDC_APPOINTMENTEDITOR_STATIC_DTEND 1041
#define IDC_APPOINTMENTEDITOR_DATETIMEPICKER_DTSTARTDATE 1042
#define IDC_APPOINTMENTEDITOR_DATETIMEPICKER_DTENDDATE 1043
#define IDC_APPOINTMENTEDITOR_STATIC_RECURRENCE 1045
#define IDC_APPOINTMENTEDITOR_STATIC_AALARM 1046
#define IDC_APPOINTMENTEDITOR_STATIC_DESCRIPTION 1047
#define IDC_APPOINTMENTEDITOR_COMBO_DTSTARTTIME 1048
#define IDC_APPOINTMENTEDITOR_STATIC_CATEGORIES 1048
#define IDC_APPOINTMENTEDITOR_COMBO_DTENDTIME 1049
#define IDC_APPOINTMENTEDITOR_COMBO_RECURRENCE 1050
#define IDC_APPOINTMENTEDITOR_COMBO_AALARMTIME 1051
#define IDC_APPOINTMENTEDITOR_EDIT_DESCRIPTION 1052
#define IDC_APPOINTMENTEDITOR_DATETIMEPICKER_DTSTARTTIME 1053
#define IDC_APPOINTMENTEDITOR_COMBO_CATEGORIES 1054
#define IDC_RICHEDIT23                  1056
#define IDC_APPOINTMENTEDITOR_DATETIMEPICKER_DTENDTIME 1058
#define IDC_DATETIMEPICKER1             1068
#define IDC_DATETIMEPICKER2             1069
#define IDC_COMBO_DEVICE                1070
#define IDC_DURATION_ALL_CHECK          1072
#define IDC_COMBO_SOURCE_DEVICE         1074
#define IDC_RADIO_All                   1075
#define IDC_RADIO_DURATION              1076
#define IDC_SYNC_ALL_CHECK              1077
#define IDC_SYNC_ALL_CHECK2             1078
#define IDC_DATETIMEPICKER_STARTAFTER   1082
#define IDC_DATETIMEPICKER_STARTBEFORE  1083

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
