{Header
}
{Description
}
{Code
0000 waitinput %var1 COMPort
0001 waitinput %var2 Input
0002 Run MobileToolKit_StaticMD.dll CaptureScreenshot %var1
0003 comparetrue 0006
0004 print "Fail to CaptureScreenshot API"
0005 comparefalse 9999
0006 Run QisdaEFsModule_StaticMD.dll EFS_ReadFile %var1 QPSTDispCapture.bmp Capture.bmp
0007 comparetrue 0010
0008 print "Fail to EFS_ReadFile API"
0009 comparefalse 9999
0010 print "Success to CaptureScreenshot API ,Capture.bmp"
}