//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Phonebook_version2.rc
//
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT 1037
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT2 1038
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT3 1039
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT4 1040
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT5 1041
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT6 1042
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT7 1043
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT8 1044
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT9 1045
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT10 1046
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT11 1047
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT12 1048
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT13 1049
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT14 1050
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT15 1051
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT16 1052
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT17 1053
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT18 1054
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT19 1055
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT20 1056
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT21 1057
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT22 1058
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT23 1059
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT24 1060
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT25 1061
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT26 1062
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT27 1063
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT28 1064
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT29 1065
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT30 1066
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT31 1067
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT32 1068
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT33 1069
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT34 1070
#define IDC_APPOINTMENTEDITOR_STATIC_SUBJECT35 1071
#define IDC_PHONEBOOK_TREE              2000
#define IDD_PHONEBOOK_VIEW              2001
#define IDC_DISPLAY_BUTTON              2002
#define IDC_PHONEBOOK_BTN_NEW           2002
#define IDD_PHONEBOOK_TREE              2003
#define IDD_PHONEBOOK_CONTACT           2004
#define IDD_PHONEBOOK_SIMCONTACT        2006
#define IDD_SYNC_OUTLOOK_DIALOG         2007
#define IDC_GROUPTREE                   3002
#define IDC_CONTACTLIST                 3003
#define IDC_PHONEBOOK_BTN_EDIT          3004
#define IDC_PHONEBOOK_BTN_DELETE        3005
#define IDC_PHONEBOOK_BTN_BACKUP        3006
#define IDC_PHONEBOOK_BTN_RESTORE       3007
#define IDC_PHONEBOOK_BTN_UPDATE        3008
#define IDC_CONTACT_NAME                3010
#define IDC_CONTACT_FIRSTNAME           3010
#define IDC_CONTACT_PRIVATE_NUMBER      3011
#define IDC_CONTACT_BUSINESS_NUMBER     3012
#define IDC_CONTACT_PRIVATE_CELL        3013
#define IDC_CONTACT_BUSINESS_CELL       3014
#define IDC_CONTACT_PRIVATE_EMAIL       3015
#define IDC_CONTACT_PRIVATE_EMAIL2      3016
#define IDC_CONTACT_PRIVATE_URL         3017
#define IDC_CONTACT_PRIVATE_FAX         3018
#define IDC_CONTACT_PRIVATEADDRESS_STREET 3019
#define IDC_CONTACT_PRIVATEADDRESS_CITY 3020
#define IDC_CONTACT_PRIVATEADDRESS_POSTALCODE 3021
#define IDC_CONTACT_PRIVATEADDRESS_STATE 3022
#define IDC_CONTACT_PRIVATEADDRESS_COUNTRY 3023
#define IDC_CONTACT_PRIVATEADDRESS_EXTRA 3024
#define IDC_CONTACT_BUSINESSADDRESS_STREET 3026
#define IDC_DATETIMEPICKER1             3027
#define IDC_CONTACT_DATETIMEPICKER_BDAY 3027
#define IDC_CONTACT_GROUP               3028
#define IDC_CONTACT_COMBO_GROUP         3028
#define IDC_CONTACT_DISPLAY             3029
#define IDC_CONTACT_BUSINESS_EMAIL      3030
#define IDC_CONTACT_BUSINESS_EMAIL2     3031
#define IDC_CONTACT_BUSINESS_URL        3032
#define IDC_CONTACT_BUSINESS_FAX        3033
#define IDC_CONTACT_BUSINESS_COMPANY    3034
#define IDC_CONTACT_BUSINESS_TITLE      3035
#define IDC_CONTACT_BUSINESSADDRESS_CITY 3036
#define IDC_CONTACT_BUSINESSADDRESS_POSTALCODE 3037
#define IDC_CONTACT_BUSINESSADDRESS_STATE 3038
#define IDC_CONTACT_BUSINESSADDRESS_EXTRA 3039
#define IDC_CONTACT_BUSINESSADDRESS_COUNTRY 3040
#define IDC_CONTACT_PRIVATE_NOTE        3042
#define IDC_CONTACT_BUSINESS_NOTE       3043
#define IDC_COMBO_TARGET_DEVICE         3047
#define IDC_COMBO2                      3048
#define IDC_COMBO_SOURCE_DEVICE         3048
#define IDC_SIM_NAME                    3049
#define IDC_SIM_PHONE                   3050
#define IDC_CONTACT_SECONDNAME          3051
#define IDC_CONTACT_LASTNAME            3051
#define IDC_RADIO1                      3052
#define IDC_RADIO2                      3053

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2008
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3054
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
