////////////////////////////////////////////////////////////////////////////
/*************************************************************************
 * Purpose: Define constant for message handling.
 * 2004/10/19 Embert Tsai
 **************************************************************************/
////////////////////////////////////////////////////////////////////////////

#ifndef DLCONSTANTDEF_H
#define DLCONSTANTDEF_H

#define DLOAD_STATUS_ERROR_MASK				0xF00

#define DL_SUCCESS(RETURN_CODE) (((RETURN_CODE)&DLOAD_STATUS_ERROR_MASK) == 0)

#define DLOAD_STATUS_COM_OPEN				0x001
#define DLOAD_STATUS_COM_CONNECTED			0x002
#define DLOAD_STATUS_DIAG_CONNECTED			0x003
#define DLOAD_STATUS_DL_CONNECTED			0x004
#define DLOAD_STATUS_STOP					0x005
#define DLOAD_STATUS_MINI_DLOAD				0x006
#define DLOAD_STATUS_START_DLOAD			0x007
#define DLOAD_STATUS_NV_ERASING				0x008
#define DLOAD_STATUS_LOADING				0x009
#define DLOAD_STATUS_DONE					0x00A
#define DLOAD_STATUS_IDLE					0x00B
#define DLOAD_STATUS_IMG_BCAKUP				0x00C
#define DLOAD_STATUS_IMG_COPYING			0x00D
#define DLOAD_STATUS_BEFORE_RETURN			0x00E
#define DLOAD_STATUS_READING				0x010
#define DLOAD_COMPARE_DONE					0x011
#define DLOAD_STATUS_BEGINDLOAD				0x012
#define DLOAD_STATUS_MFGID_START			0x013
#define DLOAD_STATUS_MFGID_END				0x014
#define DLOAD_STATUS_UPDATE_COMPLETE		0x015
#define DLOAD_STATUS_PROGRESS_UPDATE		0x016
#define DLOAD_STATUS_PREPARE_STOP			0x017
#define DLOAD_STATUS_NO_OPERATION			0x018
#define DLOAD_STATUS_INIT_DLOAD				0x019
#define DLOAD_STATUS_SD_START				0x01A
#define DLOAD_STATUS_SD_QUERY				0x01B
#define DLOAD_STATUS_SD_COMPLETE			0x01C
#define DLOAD_STATUS_LP_COMPLETE			0x01D
#define DLOAD_STATUS_OP_COMPLETE			0x01E
#define DLOAD_STATUS_NV_CMD_IMG_ERASE_COMPLETE	0x01F
#define DLOAD_STATUS_NV_CMD_IMG_RESTORE_COMPLETE	0x020
#define DLOAD_STATUS_NV_CMD_IMG_UPDATE_COMPLETE	0x021
#define DLOAD_STATUS_LP_VERSION_QUERY		0x022
#define DLOAD_STATUS_LP_SIZE_QUERY			0x023
#define DLOAD_STATUS_OP_VERSION_QUERY		0x024
#define DLOAD_STATUS_OP_SIZE_QUERY			0x025
#define DLOAD_STATUS_RESTART_COM			0x026
#define DLOAD_STATUS_FLASH_ERASING			0x027
#define DLOAD_STATUS_JDL_START				0x030
#define DLOAD_STATUS_JDL_T32_INIT			0x031
#define DLOAD_STATUS_JDL_RUN_CMM			0x032
#define DLOAD_STATUS_JDL_END				0x033

// Define constant for end user tools.
#define DLOAD_STATUS_EU_CHECK_VERSION		0x060
#define DLOAD_STATUS_EU_INIT				0x061
#define DLOAD_STATUS_EU_START_WRITE			0x062
#define DLOAD_STATUS_EU_FINAL				0x063
#define DLOAD_STATUS_EU_GO					0x064
#define DLOAD_STATUS_EU_END					0x065
//////////////////////////////////////////////////////////////////////////////////////////////////////////
#define DLOAD_STATUS_COM_NOT_CONNECTED		0xF01
#define DLOAD_STATUS_NO_MINILOAD_FILE		0xF02
#define DLOAD_STATUS_FAIL_DLOAD				0xF03
#define DLOAD_STATUS_INVALID_ESN			0xF04
#define DLOAD_STATUS_NV_ERROR				0xF05
#define DLOAD_STATUS_NV_FLASH_ERROR			0xF06
#define DLOAD_STATUS_NV_VERIFY_ERROR		0xF07
#define DLOAD_STATUS_FILE_OPEN_ERROR		0xF08
#define DLOAD_STATUS_FILE_READ_ERROR		0xF09
#define DLOAD_STATUS_COM_SERVER_FAILED		0xF0A
#define DLOAD_STATUS_DIAG_MODE_FAILED		0xF0B
#define DLOAD_STATUS_DL_MODE_FAILED			0xF0C
#define DLOAD_STATUS_MFGID_FAILED			0xF0D
#define DLOAD_STATUS_OFFLINE_FAILED			0xF0E
#define DLOAD_STATUS_RESET_FAILED			0xF0F
#define	DLOAD_STATUS_IMG_BCAKUP_FAIL		0xF10
#define	DLOAD_STATUS_FLASH_INIT_FAIL		0xF11
#define DLOAD_STATUS_SD_FAIL				0xF12
#define DLOAD_INVALID_PARAMETER				0xF13
#define DLOAD_STATUS_COM_NOT_FOUND			0xF14
#define DLOAD_STATUS_DIAG_NOT_CONNECTED		0xF15
#define DLOAD_STATUS_UNKNOWN_CMD			0xF16
#define DLOAD_STATUS_INTERNAL_ERROR			0xF17
#define DLOAD_STATUS_FLASH_ERROR			0xF18
#define DLOAD_STATUS_CRC_ERROR				0xF19
#define DLOAD_STATUS_INVALID_SW_LOAD		0xF90
//////////////////// LP download  //////////////////////////////////////////////////////////////////////////
#define DLOAD_STATUS_LP_INVALID_VERSION		0xF20
#define DLOAD_STATUS_LP_BENQ_NOT_FOUND		0xF21
#define DLOAD_STATUS_LP_INVALID_SIZE		0xF22
#define DLOAD_STATUS_LP_FILE_OPEN_FAIL		0xF23
#define DLOAD_STATUS_LP_PACKET_FAIL			0xF24
#define DLOAD_STATUS_LP_INIT_FAILED			0xF25
#define DLOAD_STATUS_LP_RESET_FAILED		0xF26
#define DLOAD_STATUS_LP_BAD_VER_LEN			0xF27
#define DLOAD_STATUS_LP_BAD_VER				0xF28
#define DLOAD_STATUS_LP_SIZE_TOO_LONG		0xF29
#define DLOAD_STATUS_LP_DL_NOT_INIT			0xF2A
#define DLOAD_STATUS_LP_BAD_OFFSET			0xF2B
#define DLOAD_STATUS_LP_ZERO_DATA_LEN		0xF2C
#define DLOAD_STATUS_LP_RCV_SIZE_TOO_BIG	0xF2D
/////////////////// OP download //////////////////////////////////////////////////////////////////////////
#define DLOAD_STATUS_OP_INVALID_VERSION		0xF30
#define DLOAD_STATUS_OP_BENQ_NOT_FOUND		0xF31
#define DLOAD_STATUS_OP_INVALID_SIZE		0xF32
#define DLOAD_STATUS_OP_FILE_OPEN_FAIL		0xF33
#define DLOAD_STATUS_OP_PACKET_FAIL			0xF34
#define DLOAD_STATUS_OP_INIT_FAILED			0xF35
#define DLOAD_STATUS_OP_RESET_FAILED		0xF36
#define DLOAD_STATUS_OP_BAD_VER_LEN			0xF37
#define DLOAD_STATUS_OP_BAD_VER				0xF38
#define DLOAD_STATUS_OP_SIZE_TOO_LONG		0xF39
#define DLOAD_STATUS_OP_DL_NOT_INIT			0xF3A
#define DLOAD_STATUS_OP_BAD_OFFSET			0xF3B
#define DLOAD_STATUS_OP_ZERO_DATA_LEN		0xF3C
#define DLOAD_STATUS_OP_RCV_SIZE_TOO_BIG	0xF3D
/////////////////// NV Command //////////////////////////////////////////////////////////////////////////
#define DLOAD_STATUS_NV_CMD_ISSUE_FAILED		0xF47
/////////////////// JDL //////////////////////////////////////////////////////////////////////////
#define DLOAD_STATUS_JDL_T32_FAILED			0xF50
#define DLOAD_STATUS_JDL_RUN_FAILED			0xF51
/////////////////////////////////////////////////////////////////////////////////////////////////////
// define error code for end user tools.
#define DLOAD_STATUS_EU_CHECK_VERSION_FAILED		0xF60
#define DLOAD_STATUS_EU_INIT_FAILED					0xF61
#define DLOAD_STATUS_EU_WRITE_FAILED				0xF62
#define DLOAD_STATUS_EU_FINAL_FAILED				0xF63
#define DLOAD_STATUS_EU_GO_FAILED					0xF64
#define DLOAD_STATUS_EU_CRC_FAILED					0xF65
#define DLOAD_STATUS_EU_ACC_FAILED					0xF66

#define DLOAD_UNKNOW_ERROR					0xFFF

/*Download mode Message Base number*/
#define WM_DLOAD_BASE						0x200     
     
#define	WM_DLOAD_STATUS						WM_USER+WM_DLOAD_BASE+1
#define WM_DLOAD_PROGRESS					WM_USER+WM_DLOAD_BASE+2
#define WM_DLOAD_TIME						WM_USER+WM_DLOAD_BASE+3

#define	WM_DLOAD_LOOP_SUCCESS				WM_USER+WM_DLOAD_BASE+0x20
#define WM_DLOAD_LOOP_FAILURE				WM_USER+WM_DLOAD_BASE+0x21
#define WM_DLOAD_LOOP_STOP					WM_USER+WM_DLOAD_BASE+0x22
#define WM_DLOAD_LOOP_STOP_ENABLE			WM_USER+WM_DLOAD_BASE+0x23
#define WM_DLOAD_LOOP_CLOSE					WM_USER+WM_DLOAD_BASE+0x24

// Define error code for download module
// Error code definition
// 0xFXXXXXXX
// First 3 X --> Module Code.
// Second 2X --> Class Code.
// Last 2X --> Erro number
#define DOWNLOAD_MODULE_CODE	0x0010000

#define CLASS_DLOPERATOR_CODE	0X0000100
#define CLASS_DLPARAMETER_CODE	0X0000200
#define CLASS_CLOADMERGER_CODE	0X0000300

// Download opeartor error code.
#define DLOPERATOR_UNKNOWN				(ERROR_MASK|DOWNLOAD_MODULE_CODE|CLASS_DLOPERATOR_CODE| 0x00)
#define DLOPERATOR_BAD_CMD				(ERROR_MASK|DOWNLOAD_MODULE_CODE|CLASS_DLOPERATOR_CODE| 0x01)
#define DLOPERATOR_VERSION_MISMATCH		(ERROR_MASK|DOWNLOAD_MODULE_CODE|CLASS_DLOPERATOR_CODE| 0x02)
#define DLOPERATOR_BLOCK_PACKET_FAILED	(ERROR_MASK|DOWNLOAD_MODULE_CODE|CLASS_DLOPERATOR_CODE| 0x03)
#define DLOPERATOR_WRITE_PACKET_FAILED	(ERROR_MASK|DOWNLOAD_MODULE_CODE|CLASS_DLOPERATOR_CODE| 0x04)
#define DLOPERATOR_ACC_FAILED			(ERROR_MASK|DOWNLOAD_MODULE_CODE|CLASS_DLOPERATOR_CODE| 0x05)

// Download parameter error code.
#define DLPARAMETER_UNKNOWN				(ERROR_MASK|DOWNLOAD_MODULE_CODE|CLASS_DLPARAMETER_CODE| 0x00)
#define DLPARAMETER_INVALID_HEADER		(ERROR_MASK|DOWNLOAD_MODULE_CODE|CLASS_DLPARAMETER_CODE| 0x01)
#define DLPARAMETER_CRC_FAILURE			(ERROR_MASK|DOWNLOAD_MODULE_CODE|CLASS_DLPARAMETER_CODE| 0x02)
#define DLPARAMETER_FILE_WRITE_FAILURE	(ERROR_MASK|DOWNLOAD_MODULE_CODE|CLASS_DLPARAMETER_CODE| 0x03)

#define CLOADMERGER_UNKNOWN				(ERROR_MASK|DOWNLOAD_MODULE_CODE|CLASS_CLOADMERGER_CODE| 0x00)
#define CLOADMERGER_FILE_ERROR			(ERROR_MASK|DOWNLOAD_MODULE_CODE|CLASS_CLOADMERGER_CODE| 0x01)
#define CLOADMERGER_CRC_FAILURE			(ERROR_MASK|DOWNLOAD_MODULE_CODE|CLASS_CLOADMERGER_CODE| 0x02)

#endif	

