//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by QUALCOMM_IMEI_CODING.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_QUALCOMM_IMEI_CODING_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_INITIAL              129
#define IDB_BITMAP_BROWSE               130
#define IDB_BITMAP_OK                   131
#define IDB_BITMAP_EXIT                 132
#define IDB_BITMAP_START                133
#define IDB_BITMAP_CHANGE               134
#define IDD_DIALOG_PASSWORD             135
#define IDB_BITMAP_CONFIG               136
#define IDD_DIALOG_CONFIG               137
#define IDB_BITMAP_SAVE                 138
#define IDD_DIALOG_MESSAGE              139
#define IDB_BITMAP1                     141
#define IDB_BITMAP_LOG                  141
#define IDC_STATIC_MODEL_MODE           1000
#define IDC_STATIC_MODEL_NAME           1001
#define IDC_COMBO_MODEL_NAME            1002
#define IDC_STATIC_MODE_NAME            1003
#define IDC_COMBO_MODE_NAME             1004
#define IDC_STATIC_BRT_QCN_CHECK        1005
#define IDC_CHECK_BRT                   1006
#define IDC_CHECK_QCN                   1007
#define IDC_STATIC_QSWINFO_SIMDATA_CSV  1008
#define IDC_STATIC_QSWIINFO             1009
#define IDC_STATIC_SIMDATA              1010
#define IDC_COMBO_QSWINFO               1010
#define IDC_STATIC_CSV                  1011
#define IDC_STATIC_QSWIINFO2            1012
#define IDC_COMBO_CSV                   1012
#define IDC_STATIC_SIMDATA2             1013
#define IDC_STATIC_CSV2                 1014
#define IDC_STATIC_MOBILE_ID2           1015
#define IDC_STATIC_TRANS2               1016
#define IDC_STATIC_SW_HW_ME_PN          1018
#define IDC_STATIC_SW                   1019
#define IDC_COMBO_SW                    1020
#define IDC_STATIC_HW                   1021
#define IDC_COMBO_HW                    1022
#define IDC_STATIC_ME                   1023
#define IDC_COMBO_ME                    1024
#define IDC_STATIC_PN                   1025
#define IDC_COMBO_PN                    1026
#define IDC_STATIC_MECHANICAL           1026
#define IDC_BUTTON_OK                   1027
#define IDC_STATIC_TIME                 1027
#define IDC_BUTTON_EXIT                 1028
#define IDC_STATIC_PERCENT              1028
#define IDC_STATIC_TARGET_TYPE          1029
#define IDC_STATIC_TITLE                1029
#define IDC_COMBO_TARGET_TYPE           1030
#define IDC_STATIC_PPF                  1030
#define IDC_STATIC_QSNV                 1031
#define IDC_STATIC_MAL_CHECK            1031
#define IDC_STATIC_QSNV2                1032
#define IDC_CHECK_MAL                   1032
#define IDC_STATIC_TIME_STAMP_QSNV      1033
#define IDC_STATIC_SECURITY_MECHANISM_FLAG 1033
#define IDC_STATIC_TIME_STAMP_QSNV2     1034
#define IDC_CHECK_SECURITY_MECHANISM_FLAG 1034
#define IDC_STATIC_FILE_SIZE_QSNV       1035
#define IDC_STATIC_PPF_FILE             1035
#define IDC_STATIC_FILE_SIZE_QSNV2      1036
#define IDC_STATIC_SO                   1036
#define IDC_STATIC_KB_QSNV              1037
#define IDC_STATIC_QSNV_FILE            1037
#define IDC_STATIC_QZCS                 1038
#define IDC_COMBO_QVCEFS                1038
#define IDC_STATIC_QZCS2                1039
#define IDC_COMBO_QSNV                  1039
#define IDC_STATIC_TIME_STAMP_QZCS      1040
#define IDC_STATIC_DUCK_FILE            1040
#define IDC_STATIC_TIME_STAMP_QZCS2     1041
#define IDC_COMBO_QZCS                  1041
#define IDC_STATIC_FILE_SIZE_QZCS       1042
#define IDC_COMBO_QSNV2                 1042
#define IDC_COMBO_DUCK                  1042
#define IDC_STATIC_FILE_SIZE_QZCS2      1043
#define IDC_STATIC_KB_QZCS              1044
#define IDC_STATIC_QVCEFS               1045
#define IDC_STATIC_QVCEFS2              1046
#define IDC_STATIC_TIME_STAMP_QVCEFS    1047
#define IDC_STATIC_TIME_STAMP_QVCEFS2   1048
#define IDC_STATIC_FILE_SIZE_QVCEFS     1049
#define IDC_STATIC_FILE_SIZE_QVCEFS2    1050
#define IDC_STATIC_KB_QVCEFS            1051
#define IDC_STATIC_QSWINFO_SIMDATA      1052
#define IDC_STATIC_QSWINFO              1053
#define IDC_STATIC_QSWINFO2             1054
#define IDC_STATIC_TIME_STAMP_QSWINFO   1055
#define IDC_STATIC_TIME_STAMP_QSWINFO2  1056
#define IDC_STATIC_FILE_SIZE_QSWINFO    1057
#define IDC_STATIC_FILE_SIZE_QSWINFO2   1058
#define IDC_STATIC_KB_QSWINFO           1059
#define IDC_STATIC_TARGET_MODE_PN       1060
#define IDC_STATIC_TIME_ELAPSE          1061
#define IDC_STATIC_TIME_STAMP_SIMDATA   1062
#define IDC_STATIC_TIME_STAMP_SIMDATA2  1063
#define IDC_STATIC_FILE_SIZE_SIMDATA    1064
#define IDC_STATIC_FILE_SIZE_SIMDATA2   1065
#define IDC_STATIC_KB_SIMDATA           1066
#define IDC_STATIC_COM                  1067
#define IDC_EDIT_IMEI                   1068
#define IDC_STATIC_TIME_STAMP_CSV       1069
#define IDC_STATIC_TIME_STAMP_CSV2      1070
#define IDC_STATIC_FILE_SIZE_CSV        1071
#define IDC_STATIC_FILE_SIZE_CSV2       1072
#define IDC_STATIC_KB_CSV               1073
#define IDC_STATIC_TARGET               1074
#define IDC_STATIC_TARGET2              1075
#define IDC_STATIC_MODE                 1076
#define IDC_STATIC_MODE2                1077
#define IDC_STATIC_BACKUP_TYPE          1078
#define IDC_STATIC_PN2                  1079
#define IDC_STATIC_SW_HW_ME             1080
#define IDC_STATIC_BACKUP_TYPE2         1081
#define IDC_STATIC_SW2                  1082
#define IDC_STATIC_PC                   1083
#define IDC_STATIC_HW2                  1084
#define IDC_STATIC_MECHANICAL2          1085
#define IDC_STATIC_PC2                  1086
#define IDC_STATIC_TIME2                1087
#define IDC_STATIC_IMEI                 1088
#define IDC_STATIC_PROGRESS             1089
#define IDC_PROGRESS                    1090
#define IDC_STATIC_TIME3                1091
#define IDC_LIST_MESSAGE                1092
#define IDC_BUTTON_START                1093
#define IDC_BUTTON_EXIT2                1094
#define IDC_STATIC_MAL                  1095
#define IDC_EDIT_MAL                    1096
#define IDC_STATIC_MOBILE_ID            1097
#define IDC_STATIC_LOCK_INDICATOR       1098
#define IDC_CHECK_NETWORK               1099
#define IDC_CHECK_SERVICE_PROVIDER      1100
#define IDC_CHECK_CORPORATE             1101
#define IDC_CHECK_NETWORK_SUBSET        1102
#define IDC_CHECK_SIM                   1103
#define IDC_CHECK_USER_SIM              1104
#define IDC_EDIT_MAL_PART               1105
#define IDC_STATIC_IMEI_MAL             1106
#define IDC_BUTTON_CHANGE               1107
#define IDC_BUTTON_CONFIG               1108
#define IDC_STATIC_IMEI_PART            1109
#define IDC_STATIC_PASSWORD             1109
#define IDC_STATIC_MAL_PART             1110
#define IDC_EDIT_PASSWORD               1110
#define IDC_EDIT_IMEI_PART              1111
#define IDC_BUTTON_SAVE                 1111
#define IDC_STATIC_DUCK                 1112
#define IDC_STATIC_CONNCET              1113
#define IDC_STATIC_DUCK2                1113
#define IDC_STATIC_CYCLE_COUNT          1114
#define IDC_STATIC_TIME_STAMP_DUCK      1114
#define IDC_EDIT_CYCLE_COUNT            1115
#define IDC_STATIC_TIME_STAMP_DUCK2     1115
#define IDC_STATIC_TIME_OUT             1116
#define IDC_STATIC_FILE_SIZE_DUCK       1116
#define IDC_EDIT_TIME_OUT               1117
#define IDC_STATIC_FILE_SIZE_DUCK2      1117
#define IDC_STATIC_CHECK                1118
#define IDC_STATIC_KB_DUCK              1118
#define IDC_CHECK_SW                    1119
#define IDC_STATIC_TRANS                1119
#define IDC_CHECK_HW                    1120
#define IDC_STATIC_PICASSO              1120
#define IDC_CHECK_ME                    1121
#define IDC_EDIT_PICASSO                1121
#define IDC_CHECK_PROCESS               1122
#define IDC_STATIC_SO1                  1122
#define IDC_STATIC_MS                   1123
#define IDC_BUTTON_EXIT3                1123
#define IDC_STATIC_BACKUP_PATH          1124
#define IDC_STATIC_BACKUP               1125
#define IDC_STATIC_MESSAGE              1125
#define IDC_EDIT_BACKUP                 1126
#define IDC_STATIC_ERROR                1126
#define IDC_STATIC_DEBUG_INFOR          1127
#define IDC_STATIC_CHECK2               1128
#define IDC_STATIC_CHECK_STATION        1128
#define IDC_STATIC_QZCS_FILE            1128
#define IDC_CHECK_DEBUGINFO             1129
#define IDC_STATIC_QVCEFS_FILE          1129
#define IDC_CHECK_SW2                   1130
#define IDC_CHECK_BASE_BAND             1130
#define IDC_EDIT_SO                     1130
#define IDC_CHECK_HW2                   1131
#define IDC_CHECK_CAL_PRE_TEST_2G       1131
#define IDC_CHECK_ME2                   1132
#define IDC_CHECK_CAL_PRE_TEST_3G       1132
#define IDC_CHECK_PROCESS2              1133
#define IDC_CHECK_LEAKAGE_CHARGER       1133
#define IDC_CHECK_FUNCTION_WIRELESS     1134
#define IDC_CHECK_FLEX_OPTION           1135
#define IDC_STATIC_PICS                 1136
#define IDC_CHECK_ACM_BOARD             1137
#define IDC_EDIT_PICS                   1138
#define IDC_CHECK_PICS                  1139
#define IDC_BUTTON1                     1141
#define IDC_BUTTON_LOG                  1141

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1142
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
