//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GPRSMdmSetupWiz.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_PROPPAGE1                   105
#define IDD_PROPPAGE2                   106
#define IDD_PROPPAGE3                   107
#define IDD_PROPPAGE4                   108
#define IDD_PROPPAGE5                   109
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_GPRSMDMPIC1          130
#define IDB_BITMAP_GPRSMDMPIC2          131
#define IDB_BITMAP_GPRSMDMPIC3          132
#define IDB_BITMAP_GPRSMDMPIC4          133
#define IDB_BITMAP_GPRSMDMPIC5          134
#define IDC_STATIC_PREPERTY_PAGE_PIC1   1000
#define IDC_STATIC_PREPERTY_PAGE_PIC2   1001
#define IDC_STATIC_PREPERTY_PAGE_PIC3   1002
#define IDC_STATIC_PREPERTY_PAGE_PIC4   1003
#define IDC_STATIC_PREPERTY_PAGE_PIC5   1004
#define IDC_STATIC_PREPERTY_PAGE1_TEXT_LINE1 1005
#define IDC_STATIC_PREPERTY_PAGE1_TEXT_LINE2 1006
#define IDC_STATIC_PREPERTY_PAGE1_TEXT_LINE3 1007
#define IDC_STATIC_PREPERTY_PAGE1_TEXT_LINE4 1008
#define IDC_STATIC_PREPERTY_PAGE1_TEXT_LINE5 1009
#define IDC_STATIC_PREPERTY_PAGE2_TEXT_LINE1 1010
#define IDC_STATIC_PREPERTY_PAGE2_TEXT_LINE2 1011
#define IDC_STATIC_PREPERTY_PAGE3_TEXT_LINE1 1012
#define IDC_STATIC_PREPERTY_PAGE3_TEXT_LINE2 1013
#define IDC_COMBO_PREPERTY_PAGE3_COMPORT 1014
#define IDC_STATIC_PREPERTY_PAGE3_TEXT_LINE3 1015
#define IDC_EDIT_PREPERTY_PAGE3_APN     1016
#define IDC_STATIC_PREPERTY_PAGE4_TEXT_LINE1 1017
#define IDC_STATIC_PREPERTY_PAGE4_TEXT_LINE2 1018
#define IDC_STATIC_PREPERTY_PAGE4_TEXT_LINE4 1019
#define IDC_STATIC_PREPERTY_PAGE4_TEXT_LINE5 1020
#define IDC_STATIC_PREPERTY_PAGE4_TEXT_LINE6 1021
#define IDC_EDIT_PREPERTY_PAGE4_DIALUP_CONNECTION_NAME 1022
#define IDC_EDIT_PREPERTY_PAGE4_DIALUP_NUMBER 1023
#define IDC_EDIT_PREPERTY_PAGE4_DIALUP_USERNAME 1024
#define IDC_EDIT_PREPERTY_PAGE4_DIALUP_PASSWORD 1025
#define IDC_STATIC_PREPERTY_PAGE5_TEXT_LINE1 1026
#define IDC_STATIC_PREPERTY_PAGE5_TEXT_LINE2 1027
#define IDC_RADIO_PREPERTY_PAGE5_REBOOT_NOW 1028
#define IDC_RADIO_PREPERTY_PAGE5_REBOOT_LATER 1029
#define IDS_PROPSHT_CAPTION             2000
#define IDS_GPRSMDM_PROPERTY_PAGE1_CAPTION 2001
#define IDS_GPRSMDM_PROPERTY_PAGE2_CAPTION 2002
#define IDS_GPRSMDM_PROPERTY_PAGE3_CAPTION 2003
#define IDS_GPRSMDM_PROPERTY_PAGE4_CAPTION 2004
#define IDS_GPRSMDM_PROPERTY_PAGE5_CAPTION 2005
#define IDS_STATIC_PREPERTY_PAGE1_TEXT_LINE1 2006
#define IDS_STATIC_PREPERTY_PAGE2_TEXT_LINE1 2007
#define IDS_STATIC_PREPERTY_PAGE3_TEXT_LINE1 2008
#define IDS_STATIC_PREPERTY_PAGE4_TEXT_LINE1 2009
#define IDS_STATIC_PREPERTY_PAGE5_TEXT_LINE1 2010
#define IDS_STATIC_PREPERTY_PAGE1_TEXT_LINE2 2011
#define IDS_STATIC_PREPERTY_PAGE1_TEXT_LINE3 2012
#define IDS_STATIC_PREPERTY_PAGE1_TEXT_LINE4 2013
#define IDS_STATIC_PREPERTY_PAGE1_TEXT_LINE5 2014
#define IDS_STATIC_PREPERTY_PAGE2_TEXT_LINE2 2015
#define IDS_STATIC_PREPERTY_PAGE3_TEXT_LINE2 2016
#define IDS_STATIC_PREPERTY_PAGE3_TEXT_LINE3 2017
#define IDS_STATIC_PREPERTY_PAGE4_TEXT_LINE2 2018
#define IDS_STATIC_PREPERTY_PAGE4_TEXT_LINE4 2019
#define IDS_STATIC_PREPERTY_PAGE4_TEXT_LINE5 2020
#define IDS_STATIC_PREPERTY_PAGE4_TEXT_LINE6 2021
#define IDS_STATIC_PREPERTY_PAGE5_TEXT_LINE2 2022
#define IDS_RADIO_PREPERTY_PAGE5_REBOOT_NOW 2023
#define IDS_RADIO_PREPERTY_PAGE5_REBOOT_LATER 2024
#define IDS_GPRSMDM_NO_MOBILE_PHONE_DETECTED 2025
#define IDS_GPRSMDM_COMPORTID_EMPTY     2026
#define IDS_GPRSMDM_APN_EMPTY           2027
#define IDS_GPRSMDM_CONNECTIONNAME_EMPTY 2028
#define IDS_GPRSMDM_DIALNUMBER_EMPTY    2029
#define IDS_STATIC_PREPERTY_PAGE2_TEXT_LINE3 2030
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
